var JOURNAL = [
  {"evenements":["carotte","exercice","week-end"],"ecureuil":false},
  {"evenements":["pain","gâteau","se brosser les dents","week-end","toucher un arbre"],"ecureuil":false},
  {"evenements":["carotte","nachos","se brosser les dents","vélo","week-end"],"ecureuil":false},
  {"evenements":["chou de Bruxelles","glace","se brosser les dents","ordinateur","week-end"],"ecureuil":false},
  {"evenements":["patates","sucrerie","se brosser les dents","exercice","week-end","dentiste"],"ecureuil":false},
  {"evenements":["chou de Bruxelles","gâteau","se brosser les dents","courir","week-end"],"ecureuil":false},
  {"evenements":["pizza","se brosser les dents","ordinateur","travail","toucher un arbre"],"ecureuil":false},
  {"evenements":["pain","bière","se brosser les dents","vélo","travail"],"ecureuil":false},
  {"evenements":["chou-fleur","se brosser les dents","travail"],"ecureuil":false},
  {"evenements":["pizza","se brosser les dents","vélo","travail"],"ecureuil":false},
  {"evenements":["lasagne","nachos","se brosser les dents","travail"],"ecureuil":false},
  {"evenements":["se brosser les dents","week-end","toucher un arbre"],"ecureuil":false},
  {"evenements":["salade","se brosser les dents","télévision","week-end"],"ecureuil":false},
  {"evenements":["spaghetti","se brosser les dents","travail"],"ecureuil":false},
  {"evenements":["se brosser les dents","ordinateur","travail"],"ecureuil":false},
  {"evenements":["salade","nachos","se brosser les dents","travail"],"ecureuil":false},
  {"evenements":["carotte","se brosser les dents","courir","travail"],"ecureuil":false},
  {"evenements":["se brosser les dents","travail"],"ecureuil":false},
  {"evenements":["chou-fleur","lire","week-end"],"ecureuil":false},
  {"evenements":["pain","se brosser les dents","week-end"],"ecureuil":false},
  {"evenements":["lasagne","se brosser les dents","exercice","travail"],"ecureuil":false},
  {"evenements":["spaghetti","se brosser les dents","lire","travail"],"ecureuil":false},
  {"evenements":["carotte","glace","se brosser les dents","télévision","travail"],"ecureuil":false},
  {"evenements":["spaghetti","nachos","travail"],"ecureuil":false},
  {"evenements":["chou-fleur","glace","se brosser les dents","vélo","travail"],"ecureuil":false},
  {"evenements":["spaghetti","cacahuètes","ordinateur","week-end"],"ecureuil":true},
  {"evenements":["patates","glace","se brosser les dents","ordinateur","week-end"],"ecureuil":false},
  {"evenements":["patates","glace","se brosser les dents","travail"],"ecureuil":false},
  {"evenements":["cacahuètes","se brosser les dents","courir","travail"],"ecureuil":false},
  {"evenements":["patates","exercice","travail"],"ecureuil":false},
  {"evenements":["pizza","glace","ordinateur","travail"],"ecureuil":false},
  {"evenements":["lasagne","glace","travail"],"ecureuil":false},
  {"evenements":["chou-fleur","sucrerie","lire","week-end"],"ecureuil":false},
  {"evenements":["lasagne","nachos","se brosser les dents","courir","week-end"],"ecureuil":false},
  {"evenements":["patates","se brosser les dents","travail"],"ecureuil":false},
  {"evenements":["carotte","travail"],"ecureuil":false},
  {"evenements":["pizza","bière","travail","dentiste"],"ecureuil":false},
  {"evenements":["lasagne","gâteau","vélo","travail"],"ecureuil":false},
  {"evenements":["spaghetti","se brosser les dents","lire","travail"],"ecureuil":false},
  {"evenements":["spaghetti","gâteau","télévision","week-end"],"ecureuil":false},
  {"evenements":["pain","se brosser les dents","exercice","week-end"],"ecureuil":false},
  {"evenements":["lasagne","cacahuètes","travail"],"ecureuil":true},
  {"evenements":["pizza","travail"],"ecureuil":false},
  {"evenements":["patates","exercice","travail"],"ecureuil":false},
  {"evenements":["se brosser les dents","exercice","travail"],"ecureuil":false},
  {"evenements":["spaghetti","se brosser les dents","télévision","travail"],"ecureuil":false},
  {"evenements":["pizza","vélo","week-end"],"ecureuil":false},
  {"evenements":["carotte","se brosser les dents","week-end"],"ecureuil":false},
  {"evenements":["carotte","bière","se brosser les dents","travail"],"ecureuil":false},
  {"evenements":["pizza","cacahuètes","sucrerie","travail"],"ecureuil":true},
  {"evenements":["carotte","cacahuètes","se brosser les dents","lire","travail"],"ecureuil":false},
  {"evenements":["patates","cacahuètes","se brosser les dents","travail"],"ecureuil":false},
  {"evenements":["carotte","nachos","se brosser les dents","exercice","travail"],"ecureuil":false},
  {"evenements":["pizza","cacahuètes","se brosser les dents","télévision","week-end"],"ecureuil":false},
  {"evenements":["lasagne","se brosser les dents","vélo","week-end"],"ecureuil":false},
  {"evenements":["chou-fleur","cacahuètes","se brosser les dents","ordinateur","travail","toucher un arbre"],"ecureuil":false},
  {"evenements":["salade","se brosser les dents","télévision","travail"],"ecureuil":false},
  {"evenements":["patates","se brosser les dents","ordinateur","travail"],"ecureuil":false},
  {"evenements":["pain","sucrerie","travail"],"ecureuil":false},
  {"evenements":["patates","nachos","travail"],"ecureuil":false},
  {"evenements":["carotte","gâteau","se brosser les dents","week-end"],"ecureuil":false},
  {"evenements":["carotte","se brosser les dents","exercice","week-end","toucher un arbre"],"ecureuil":false},
  {"evenements":["chou de Bruxelles","courir","travail"],"ecureuil":false},
  {"evenements":["se brosser les dents","travail"],"ecureuil":false},
  {"evenements":["salade","se brosser les dents","courir","travail"],"ecureuil":false},
  {"evenements":["sucrerie","se brosser les dents","travail"],"ecureuil":false},
  {"evenements":["chou de Bruxelles","se brosser les dents","ordinateur","travail"],"ecureuil":false},
  {"evenements":["pain","se brosser les dents","week-end"],"ecureuil":false},
  {"evenements":["chou-fleur","se brosser les dents","week-end"],"ecureuil":false},
  {"evenements":["spaghetti","sucrerie","télévision","travail","toucher un arbre"],"ecureuil":false},
  {"evenements":["carotte","gâteau","se brosser les dents","travail"],"ecureuil":false},
  {"evenements":["salade","se brosser les dents","travail"],"ecureuil":false},
  {"evenements":["carotte","glace","se brosser les dents","vélo","travail"],"ecureuil":false},
  {"evenements":["pizza","se brosser les dents","travail"],"ecureuil":false},
  {"evenements":["spaghetti","cacahuètes","exercice","week-end"],"ecureuil":true},
  {"evenements":["pain","bière","ordinateur","week-end","toucher un arbre"],"ecureuil":false},
  {"evenements":["se brosser les dents","courir","travail"],"ecureuil":false},
  {"evenements":["salade","cacahuètes","se brosser les dents","travail","toucher un arbre"],"ecureuil":false},
  {"evenements":["lasagne","se brosser les dents","télévision","travail"],"ecureuil":false},
  {"evenements":["chou-fleur","se brosser les dents","courir","travail"],"ecureuil":false},
  {"evenements":["carotte","se brosser les dents","courir","travail"],"ecureuil":false},
  {"evenements":["carotte","lire","week-end"],"ecureuil":false},
  {"evenements":["carotte","cacahuètes","lire","week-end"],"ecureuil":true},
  {"evenements":["patates","se brosser les dents","courir","travail"],"ecureuil":false},
  {"evenements":["lasagne","glace","travail","toucher un arbre"],"ecureuil":false},
  {"evenements":["chou-fleur","cacahuètes","se brosser les dents","vélo","travail"],"ecureuil":false},
  {"evenements":["pizza","se brosser les dents","courir","travail"],"ecureuil":false},
  {"evenements":["salade","se brosser les dents","travail"],"ecureuil":false},
  {"evenements":["pain","se brosser les dents","télévision","week-end"],"ecureuil":false},
  {"evenements":["chou-fleur","cacahuètes","se brosser les dents","week-end"],"ecureuil":false}
];

// This makes sure the data is exported in node.js —
// `require('./path/to/journal.js')` will get you the array.
if (typeof module != "undefined" && module.exports && (typeof window == "undefined" || window.exports != exports))
  module.exports = JOURNAL;
if (typeof global != "undefined" && !global.JOURNAL)
  global.JOURNAL = JOURNAL;
